import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Index.module.css'

// Components 

import Nav from '../components/page/Nav'

const gallery = ["/IMG_2878.JPG", "dirt.JPG", "IMG_2885.JPG", "IMG_3013.JPG", "IMG_2888.JPG"]


export default function Home() {
  const bgImg = gallery[Math.floor(Math.random() * gallery.length)];
  return (
    <div className={styles.container}>
      <Head>
        <title>Clumsyturtle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/clumsycan.png" />
      </Head>
      <Nav />
      <header id='header' className={styles.header}>
                <div className={styles.headerBg} style={{backgroundImage: `url("${bgImg}")`}}    />
                <main>
                        <h1>The Clumsy Turtle</h1>
                        <p>Discover stories <span>&</span> adventures <b>from anyone.</b></p>
                        <Link href={'/#blogs'}><button>Get Started</button></Link>
                </main>
      </header>
      <main>
          IMG_2888.JPGIMG_2888.JPG
      </main>

      fwf
      

    </div>
  )
}
