import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// Components 

import Nav from '../components/page/Nav'
import RankCard from '../components/RankCard'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Clumsyturtle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/clumsycan.png" />
      </Head>
      <Nav />
      <main>
          
      </main>

    </div>
  )
}
